version: 2
updates:
  # npm dependencies for the frontend
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"

  # pip dependencies for the backend
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"

